In [ ]:
import numpy as np

arr = np.array([2, 5, 10, 5])
print(type(arr))
print(arr)

arr2d = np.array([[2, 3], [9, 10], ['John', 'Jennie'], [4, 10], [10, 23]])
print(type(arr2d))
print(arr2d)

print(arr + 1)
print(arr * 2) # [ 4 10 20 10]

print(np.sum(arr))
print(np.mean(arr))
print(np.median(arr))
print(np.std(arr))
print(np.var(arr))
print(np.min(arr))
print(np.max(arr))

print(np.sort(arr))
print(np.unique(arr)) # similar to set

# list 
list = [2, 3, 6]
print(list * 2)


<class 'numpy.ndarray'>
[ 2  5 10  5]
<class 'numpy.ndarray'>
[['2' '3']
 ['9' '10']
 ['John' 'Jennie']
 ['4' '10']
 ['10' '23']]
[ 3  6 11  6]
[ 4 10 20 10]
22
5.5
5.0
2.8722813232690143
8.25
2
10
[ 2  5  5 10]
[ 2  5 10]
[2, 3, 6, 2, 3, 6]
