In [ ]:
import numpy as np

arr = np.array([2, 5, 10])
print(type(arr))
print(arr)

arr2d = np.array([[2, 3], [9, 10], ['John', 'Jennie'], [4, 10], [10, 23]])
print(type(arr2d))
print(arr2d)

print(arr + 1)
print(arr * 2) # [ 4 10 20]

# list 
list = [2, 3, 6]
print(list * 2)

<class 'numpy.ndarray'>
[ 2  5 10]
<class 'numpy.ndarray'>
[['2' '3']
 ['9' '10']
 ['John' 'Jennie']
 ['4' '10']
 ['10' '23']]
[ 3  6 11]
[ 4 10 20]
[2, 3, 6, 2, 3, 6]
